pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
               echo 'Hello from Jenkins Pipeline! Build'
            }
        }
        stage('Test') {
            steps {
                echo 'Hello from Jenkins Pipeline! Test'
            }
        }
        stage('Deliver') { 
            steps {
                echo 'Hello from Jenkins Pipeline! Deploy'
            }
        }
    }
}
