pipeline {
    agent any
    environment {
        // Dynamic environment variables
        SONAR_HOST_URL = 'https://daniel-unmaturative-overnarrowly.ngrok-free.dev'
        SONAR_TOKEN = credentials('sonarqube') // Jenkins credentials ID
    }

    tools {
          maven 'Add Maven'
          sonar 'SonarScanner' // NOT sonarQubeScanner
    }
    stages {
        stage('Build') {
            steps {
               sh 'mvn clean package'
               echo 'Hello from Jenkins Pipeline! Build'
            }
            post {
              success {
                 archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
            }
        }

        }
        stage('SonarQube Analysis') {
            steps {
                // 'MySonarQubeServer' must match the SonarQube config name in Jenkins
               withSonarQubeEnv('sonarqube') {
            sh """
                sonar-scanner \
                -Dsonar.projectKey=my-sample-project \
                -Dsonar.projectName='My Sample Project' \
                -Dsonar.projectVersion=1.0 \
                -Dsonar.sources=src \
                -Dsonar.host.url=${SONAR_HOST_URL} \
                -Dsonar.login=${SONAR_TOKEN} \
                -Dsonar.java.binaries=build/classes
            """
        }
            }
        }
    }
}
