pipeline {
    agent any
    environment {
        // Dynamic environment variables
        SONAR_HOST_URL = 'https://daniel-unmaturative-overnarrowly.ngrok-free.dev'
        SONAR_TOKEN = credentials('sonarqube') // Jenkins credentials ID
    }

    tools {
          maven 'Add Maven'
    }
    stages {
        stage('Build') {
            steps {
               sh 'mvn clean package'
               echo 'Hello from Jenkins Pipeline! Build'
            }
            post {
              success {
                 archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
            }
        }

        }
        stage('SonarQube Analysis') {
            steps {
                // 'MySonarQubeServer' must match the SonarQube config name in Jenkins
               withSonarQubeEnv('sonarqube') {
            sh '''
                        docker run --rm \
                        -e SONAR_HOST_URL=$SONAR_HOST_URL \
                        -e SONAR_LOGIN=$SONAR_TOKEN \
                        -v $(pwd):/usr/src \
                        sonarsource/sonar-scanner-cli \
                        -Dsonar.projectKey=my-sample-project \
                        -Dsonar.projectName='My Sample Project' \
                        -Dsonar.sources=src \
                        -Dsonar.java.binaries=target/classes
                    '''
        }
            }
        }
    }
}
